catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1633
  vitest: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1633
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1633
overrides:
  vite: "catalog:"
  vitest: "catalog:"
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
